import { Theme } from '@/src/types/deck';

export const corporate: Theme = {
  name: 'Corporate',
  backgrounds: {
    title: '#ffffff',
    context: '#ffffff',
    problem: '#ffffff',
    finding: '#ffffff',
    insight: '#ffffff',
    recommendation: '#ffffff',
    proof: '#ffffff',
    exhibit: '#ffffff',
    structure: '#ffffff',
    closing: '#ffffff',
  },
  accents: {
    title: '#1B3A6B',
    context: '#1B3A6B',
    problem: '#9B2C2C',
    finding: '#1B3A6B',
    insight: '#1B3A6B',
    recommendation: '#1B3A6B',
    proof: '#1B3A6B',
    exhibit: '#1B3A6B',
    structure: '#1B3A6B',
    closing: '#1B3A6B',
  },
  badges: {
    title: { background: '#e2e8f0', color: '#1B3A6B' },
    context: { background: '#e2e8f0', color: '#1B3A6B' },
    problem: { background: '#fed7d7', color: '#9B2C2C' },
    finding: { background: '#e2e8f0', color: '#1B3A6B' },
    insight: { background: '#e2e8f0', color: '#1B3A6B' },
    recommendation: { background: '#e2e8f0', color: '#1B3A6B' },
    proof: { background: '#e2e8f0', color: '#1B3A6B' },
    exhibit: { background: '#e2e8f0', color: '#1B3A6B' },
    structure: { background: '#e2e8f0', color: '#1B3A6B' },
    closing: { background: '#e2e8f0', color: '#1B3A6B' },
  },
  typography: {
    headlineLg: '30px',
    headlineMd: '21px',
    body: '#1a202c',
    muted: '#718096',
    eyebrow: 'uppercase tracking-wider text-xs font-semibold',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  decorative: {
    useDarkSlides: false,
    useDecoCircles: false,
    accentBarWidth: '4px',
    cardBackground: '#f0f4f8',
    cardBorder: '0.5px solid #e2e8f0',
  },
};
