import { Theme } from '@/src/types/deck';

export const editorial: Theme = {
  name: 'Editorial',
  backgrounds: {
    title: '#1a1a2e',
    context: '#ffffff',
    problem: '#ffffff',
    finding: '#ffffff',
    insight: '#1a1a2e',
    recommendation: '#ffffff',
    proof: '#ffffff',
    exhibit: '#ffffff',
    structure: '#ffffff',
    closing: '#0f1923',
  },
  accents: {
    title: '#7F77DD',
    context: '#7F77DD',
    problem: '#E24B4A',
    finding: '#7F77DD',
    insight: '#7F77DD',
    recommendation: '#7F77DD',
    proof: '#7F77DD',
    exhibit: '#7F77DD',
    structure: '#7F77DD',
    closing: '#7F77DD',
  },
  badges: {
    title: { background: 'rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.8)' },
    context: { background: '#eeecfb', color: '#5b4fc4' },
    problem: { background: '#fde8e8', color: '#c03030' },
    finding: { background: '#eeecfb', color: '#5b4fc4' },
    insight: { background: 'rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.8)' },
    recommendation: { background: '#eeecfb', color: '#5b4fc4' },
    proof: { background: '#eeecfb', color: '#5b4fc4' },
    exhibit: { background: '#eeecfb', color: '#5b4fc4' },
    structure: { background: '#eeecfb', color: '#5b4fc4' },
    closing: { background: 'rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.8)' },
  },
  typography: {
    headlineLg: '32px',
    headlineMd: '22px',
    body: '#1a1a1a',
    muted: '#6b6b6b',
    eyebrow: 'uppercase tracking-wider text-xs font-semibold',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  decorative: {
    useDarkSlides: true,
    useDecoCircles: true,
    accentBarWidth: '3px',
    cardBackground: '#f5f5f5',
    cardBorder: '0.5px solid #e5e5e5',
  },
};
